name: 'Test Report'
on:
  workflow_run:
    workflows: ['tests']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: E2E Tests
        path: '*.xml'
        reporter: java-junit
