name: 'Test'

on:
  push:
    branches: [ master, prod ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - name: Install dependencies
        run: |
          yarn install
          yarn playwright install-deps chromium 

      - name: Generate static website
        run: yarn generate

      - name: Serve static website
        run: yarn start &

      - name: Launch tests
        run: yarn e2e-test
