name: tests

on:
  push:
    branches: [ master, prod ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: |
          yarn install
      
      - name: Generate static website
        run: yarn generate
        
      - name: Serve static website
        run: yarn start &
      
      - name: Launch tests
        run: yarn e2e-test
        env:
          FOLIO_JUNIT_OUTPUT_NAME: test-results/e2e/junit.xml
        
      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/test-results/e2e/junit.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      
